# Site settings
title: Alexandria - a PBS Design & Component Library
email: component-librarian@pbs.org
description: > # this means to ignore newlines until "baseurl:"
  A Design Style Guide and Component library for PBS digital properties
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.pbs.org" # the base hostname & protocol for your site
twitter_username: pbs
github_username:  pbs

# Build settings
markdown: kramdown

# Collection Definition
collections:
  components:
    code: id
    output: true
    status: foo
    example: example
    products: foo
