# Site settings
title: PBS Component Library
email: component-librarian@pbs.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chipcullen
github_username:  chipcullen

# Build settings
markdown: kramdown

# Collection Definition
collections:
  components:
    id: id
    output: true
    status: foo
    example: example
    products: foo
